### ISSUE TITLE
Error on pg 116

### ISSUE THREAD

**Issue by SummaryPick** [markjprice/cs9dotnet5#26]
Just an FYI in case you reuse the factorial example.  0! = 1 not 0.

**Comment by markjprice** [comment]
Thanks, yes, this was fixed in the sixth and seventh editions:
https://github.com/markjprice/cs10dotnet6/blob/main/vs4win/Chapter04/WritingFunctions/Program.cs#L79
https://github.com/markjprice/cs11dotnet7/blob/main/vs4win/Chapter04/WritingFunctions/Program.Functions.cs#L95

I have also now fixed the code in this repo too.
